# Generated by Django 3.2.6 on 2021-08-23 10:15

from django.db import migrations


def apply_migration(apps, schema_editor):
    group = apps.get_model('webapp', 'TransferType')
    group.objects.bulk_create([
        group(name=u'Накталай'),
        group(name=u'Баланс'),
        group(name=u'Элсом'),
        group(name=u'О!деньги'),
        group(name=u'MegaPay'),
        group(name=u'Банк'),
    ])


class Migration(migrations.Migration):


    dependencies = [
        ('webapp', '0003_membershipfee_transfertype'),
    ]

    operations = [
        migrations.RunPython(apply_migration)
    ]
