# Generated by Django 3.2.6 on 2021-08-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210824_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Сүрөтү'),
        ),
        migrations.AlterField(
            model_name='membershipfee',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='Төлөндү'),
        ),
    ]
