# Generated by Django 3.2.6 on 2021-08-23 08:11

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Аймактын аталышы')),
            ],
            options={
                'verbose_name': 'Аймак',
                'verbose_name_plural': 'Аймактар',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Айылдын аталышы')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='webapp.region', verbose_name='Аймагы')),
            ],
            options={
                'verbose_name': 'Айыл',
                'verbose_name_plural': 'Айылдар',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Аты')),
                ('surname', models.CharField(max_length=128, verbose_name='Фамилиясы')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Суроту')),
                ('phone_number1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон 1')),
                ('phone_number2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон 2')),
                ('whatsapp_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Whatsapp номери')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Мүчө болуу тарыхы')),
                ('position', models.CharField(max_length=256, verbose_name='Кызматы')),
                ('membership_fee', models.BooleanField(default=False, verbose_name='Мүчөлүк төлөмдөн бошотулган')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='Өчүрүлгөн')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.region', verbose_name='Аймагы')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.village', verbose_name='Айылы')),
            ],
        ),
    ]
