# Generated by Django 3.2.6 on 2021-08-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_member_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Аталышы')),
            ],
            options={
                'verbose_name': 'Которуу түрү',
                'verbose_name_plural': 'Которуу түрлөрү',
            },
        ),
        migrations.CreateModel(
            name='MembershipFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Төлөм суммасы')),
                ('info', models.TextField(max_length=2048, verbose_name='Кошумча маалымат')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_payed', models.BooleanField(default=False, verbose_name='Төлөндү белгиси')),
                ('payed_at', models.DateTimeField(blank=True, null=True, verbose_name='Төлөнгөн тарыхы')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='webapp.member', verbose_name='Төлөөчү')),
                ('transfer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_fee', to='webapp.transfertype', verbose_name='Которуу түрү')),
            ],
        ),
    ]
