# Generated by Django 3.2.6 on 2021-08-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_membershipfee_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=128, verbose_name='Төлөөчү')),
                ('amount', models.PositiveIntegerField(verbose_name='Төлөм суммасы')),
                ('type', models.CharField(choices=[('income', 'Киреше'), ('expense', 'Чыгаша')], max_length=128, verbose_name='Төлөм түрү')),
                ('info', models.TextField(max_length=2048, verbose_name='Кошумча маалымат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Төлөм тарыхы')),
            ],
            options={
                'verbose_name': 'Төлөм',
                'verbose_name_plural': 'Төлөмдөр',
            },
        ),
    ]
