# Generated by Django 3.2.6 on 2021-08-24 17:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipfee',
            options={'verbose_name': 'Мүчөлүк төлөм', 'verbose_name_plural': 'Мүчөлүк төлөмдөр'},
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефону'),
        ),
        migrations.AlterField(
            model_name='membershipfee',
            name='info',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Кошумча маалымат'),
        ),
        migrations.AlterField(
            model_name='membershipfee',
            name='transfer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_fee', to='webapp.transfertype', verbose_name='Которуу түрү'),
        ),
    ]
